// Freezer Management API - Mock Data Implementation

// Mock freezer data
const mockFreezers = [
  {
    id: "1",
    name: "Main Lab Freezer",
    location: "Lab Room A",
    capacity: 500,
    temperature: "-80°C",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Backup Freezer",
    location: "Lab Room B",
    capacity: 300,
    temperature: "-80°C",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Long-term Storage",
    location: "Storage Room",
    capacity: 1000,
    temperature: "-150°C",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Research Freezer",
    location: "Research Lab",
    capacity: 400,
    temperature: "-80°C",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// Mock sample counts per freezer
const mockSampleCounts = {
  F1: 387,
  F2: 156,
  F3: 234,
  F4: 298,
}

// Mock freezer data
const mockFreezers2 = [
  {
    id: "F1",
    name: "Main Lab Freezer",
    location: "Lab Room A",
    temperature: "-80°C",
    capacity: 500,
    currentSamples: 387,
    status: "operational",
    lastMaintenance: "2024-01-10",
  },
  {
    id: "F2",
    name: "Backup Freezer",
    location: "Lab Room B",
    temperature: "-80°C",
    capacity: 300,
    currentSamples: 156,
    status: "operational",
    lastMaintenance: "2024-01-08",
  },
  {
    id: "F3",
    name: "Long-term Storage",
    location: "Storage Room",
    temperature: "-150°C",
    capacity: 1000,
    currentSamples: 234,
    status: "operational",
    lastMaintenance: "2024-01-12",
  },
  {
    id: "F4",
    name: "Research Freezer",
    location: "Research Lab",
    temperature: "-80°C",
    capacity: 400,
    currentSamples: 298,
    status: "maintenance",
    lastMaintenance: "2024-01-05",
  },
  {
    _id: "6845d4ee4f6a05a381bb6ab9",
    code: "F1",
    name: "Congelador",
    location: "Microbiologia",
    temperature: "-150°C",
    capacity: 1000,
    currentSamples: 0,
    status: "operational",
    lastMaintenance: "2025-01-10F1",
    notes: "Tecidos",
    utilizationPercentage: 0,
  }
]


// Mock data storage (in a real app, this would be in a database)
const mockSamples = [
  {
    id: "1",
    patientCode: "PT-2024-001",
    sampleType: "Blood Serum",
    project: "COVID-19 Study",
    freezerId: "F1",
    shelf: "S2",
    box: "B3",
    position: "P15",
    entryDate: "2024-01-15",
    expiryDate: "2024-07-15",
    notes: "High priority sample",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    patientCode: "PT-2024-002",
    sampleType: "Plasma",
    project: "Diabetes Research",
    freezerId: "F2",
    shelf: "S1",
    box: "B1",
    position: "P8",
    entryDate: "2024-01-14",
    expiryDate: "2024-06-14",
    notes: "Control sample",
    createdAt: "2024-01-14T09:15:00Z",
    updatedAt: "2024-01-14T09:15:00Z",
  },
  {
    id: "3",
    patientCode: "PT-2024-003",
    sampleType: "DNA",
    project: "Genetic Analysis",
    freezerId: "F1",
    shelf: "S1",
    box: "B2",
    position: "P5",
    entryDate: "2024-01-13",
    expiryDate: "2025-01-13",
    notes: "Long-term storage",
    createdAt: "2024-01-13T14:45:00Z",
    updatedAt: "2024-01-13T14:45:00Z",
  },
]

// Mock data for samples
const mockSampleData2 = [
  {
    id: "1",
    patientCode: "PT-2024-001",
    sampleType: "Blood Serum",
    project: "COVID-19 Study",
    freezerId: "F1",
    shelf: "S2",
    box: "B3",
    position: "P15",
    entryDate: "2024-01-15",
    expiryDate: "2024-07-15",
    notes: "High priority sample",
  },
  {
    id: "2",
    patientCode: "PT-2024-002",
    sampleType: "Plasma",
    project: "Diabetes Research",
    freezerId: "F2",
    shelf: "S1",
    box: "B1",
    position: "P8",
    entryDate: "2024-01-14",
    expiryDate: "2024-06-14",
    notes: "Control sample",
  },
  {
    id: "3",
    patientCode: "PT-2024-003",
    sampleType: "DNA",
    project: "Genetic Analysis",
    freezerId: "F1",
    shelf: "S1",
    box: "B2",
    position: "P5",
    entryDate: "2024-01-13",
    expiryDate: "2025-01-13",
    notes: "Long-term storage",
  },
  {
    id: "4",
    patientCode: "PT-2024-004",
    sampleType: "RNA",
    project: "Genetic Analysis",
    freezerId: "F3",
    shelf: "S3",
    box: "B1",
    position: "P12",
    entryDate: "2024-01-12",
    expiryDate: "2024-08-12",
    notes: "Research sample",
  },
  {
    id: "5",
    patientCode: "PT-2024-005",
    sampleType: "Tissue",
    project: "Cancer Research",
    freezerId: "F4",
    shelf: "S1",
    box: "B5",
    position: "P3",
    entryDate: "2024-01-11",
    expiryDate: "2025-01-11",
    notes: "Biopsy sample",
  },
  {
    id: "6",
    patientCode: "PT-2024-006",
    sampleType: "Blood Serum",
    project: "COVID-19 Study",
    freezerId: "F1",
    shelf: "S2",
    box: "B4",
    position: "P7",
    entryDate: "2024-01-10",
    expiryDate: "2024-07-10",
    notes: "Patient follow-up sample",
  },
  {
    id: "7",
    patientCode: "PT-2024-007",
    sampleType: "Plasma",
    project: "Cardiovascular Study",
    freezerId: "F2",
    shelf: "S2",
    box: "B2",
    position: "P14",
    entryDate: "2024-01-09",
    expiryDate: "2024-06-09",
    notes: "Pre-treatment sample",
  },
  {
    id: "8",
    patientCode: "PT-2024-008",
    sampleType: "DNA",
    project: "Genetic Analysis",
    freezerId: "F3",
    shelf: "S1",
    box: "B3",
    position: "P9",
    entryDate: "2024-01-08",
    expiryDate: "2025-01-08",
    notes: "Family study participant",
  },
  {
    id: "9",
    patientCode: "PT-2024-009",
    sampleType: "RNA",
    project: "Cancer Research",
    freezerId: "F4",
    shelf: "S2",
    box: "B1",
    position: "P18",
    entryDate: "2024-01-07",
    expiryDate: "2024-08-07",
    notes: "Tumor sample",
  },
  {
    id: "10",
    patientCode: "PT-2024-010",
    sampleType: "Tissue",
    project: "Cancer Research",
    freezerId: "F1",
    shelf: "S3",
    box: "B2",
    position: "P11",
    entryDate: "2024-01-06",
    expiryDate: "2025-01-06",
    notes: "Normal tissue control",
  },
  {
    id: "11",
    patientCode: "PT-2024-011",
    sampleType: "Blood Serum",
    project: "Diabetes Research",
    freezerId: "F2",
    shelf: "S1",
    box: "B3",
    position: "P22",
    entryDate: "2024-01-05",
    expiryDate: "2024-07-05",
    notes: "Baseline measurement",
  },
  {
    id: "12",
    patientCode: "PT-2024-012",
    sampleType: "Plasma",
    project: "COVID-19 Study",
    freezerId: "F3",
    shelf: "S2",
    box: "B4",
    position: "P6",
    entryDate: "2024-01-04",
    expiryDate: "2024-06-04",
    notes: "Convalescent plasma",
  },
  {
    id: "13",
    patientCode: "PT-2024-013",
    sampleType: "DNA",
    project: "Cardiovascular Study",
    freezerId: "F4",
    shelf: "S1",
    box: "B1",
    position: "P25",
    entryDate: "2024-01-03",
    expiryDate: "2025-01-03",
    notes: "Genetic risk assessment",
  },
  {
    id: "14",
    patientCode: "PT-2024-014",
    sampleType: "RNA",
    project: "Genetic Analysis",
    freezerId: "F1",
    shelf: "S2",
    box: "B5",
    position: "P13",
    entryDate: "2024-01-02",
    expiryDate: "2024-08-02",
    notes: "Expression analysis",
  },
  {
    id: "15",
    patientCode: "PT-2024-015",
    sampleType: "Tissue",
    project: "Diabetes Research",
    freezerId: "F2",
    shelf: "S3",
    box: "B1",
    position: "P4",
    entryDate: "2024-01-01",
    expiryDate: "2025-01-01",
    notes: "Pancreatic tissue",
  },
  {
    id: "16",
    patientCode: "PT-2024-016",
    sampleType: "Blood Serum",
    project: "Cancer Research",
    freezerId: "F3",
    shelf: "S1",
    box: "B2",
    position: "P19",
    entryDate: "2023-12-31",
    expiryDate: "2024-06-30",
    notes: "Post-surgery sample",
  },
  {
    id: "17",
    patientCode: "PT-2024-017",
    sampleType: "Plasma",
    project: "Genetic Analysis",
    freezerId: "F4",
    shelf: "S2",
    box: "B3",
    position: "P8",
    entryDate: "2023-12-30",
    expiryDate: "2024-06-29",
    notes: "Rare variant carrier",
  },
  {
    id: "18",
    patientCode: "PT-2024-018",
    sampleType: "DNA",
    project: "COVID-19 Study",
    freezerId: "F1",
    shelf: "S3",
    box: "B4",
    position: "P16",
    entryDate: "2023-12-29",
    expiryDate: "2024-12-29",
    notes: "Long COVID study",
  },
  {
    id: "19",
    patientCode: "PT-2024-019",
    sampleType: "RNA",
    project: "Cardiovascular Study",
    freezerId: "F2",
    shelf: "S1",
    box: "B5",
    position: "P21",
    entryDate: "2023-12-28",
    expiryDate: "2024-07-28",
    notes: "Heart failure patient",
  },
  {
    id: "20",
    patientCode: "PT-2024-020",
    sampleType: "Tissue",
    project: "Cancer Research",
    freezerId: "F3",
    shelf: "S2",
    box: "B1",
    position: "P10",
    entryDate: "2023-12-27",
    expiryDate: "2024-12-27",
    notes: "Metastatic sample",
  },
]

// Mock sample data
const mockSampleData = [
  {
    id: "1",
    patientCode: "PT-2024-001",
    sampleType: "Blood Serum",
    project: "COVID-19 Study",
    freezerId: "F1",
    shelf: "S2",
    box: "B3",
    position: "P15",
    entryDate: "2024-01-15",
    expiryDate: "2024-07-15",
    notes: "High priority sample",
  },
  {
    id: "2",
    patientCode: "PT-2024-002",
    sampleType: "Plasma",
    project: "Diabetes Research",
    freezerId: "F2",
    shelf: "S1",
    box: "B1",
    position: "P8",
    entryDate: "2024-01-14",
    expiryDate: "2024-06-14",
    notes: "Control sample",
  },
  {
    id: "3",
    patientCode: "PT-2024-003",
    sampleType: "DNA",
    project: "Genetic Analysis",
    freezerId: "F1",
    shelf: "S1",
    box: "B2",
    position: "P5",
    entryDate: "2024-01-13",
    expiryDate: "2025-01-13",
    notes: "Long-term storage",
  },
]

// Mock freezer data
const mockFreezerData4 = [
  {
    id: "F1",
    name: "Main Lab Freezer",
    location: "Lab Room A",
    temperature: "-80°C",
    capacity: 500,
    currentSamples: 387,
    status: "operational",
    lastMaintenance: "2024-01-10",
    nextMaintenance: "2024-04-10",
    alertsEnabled: true,
    temperatureAlerts: true,
    maintenanceAlerts: true,
    capacityThreshold: 90,
    notes: "Primary storage for COVID-19 study samples",
  },
  {
    id: "F2",
    name: "Backup Freezer",
    location: "Lab Room B",
    temperature: "-80°C",
    capacity: 300,
    currentSamples: 156,
    status: "operational",
    lastMaintenance: "2024-01-08",
    nextMaintenance: "2024-04-08",
    alertsEnabled: true,
    temperatureAlerts: true,
    maintenanceAlerts: false,
    capacityThreshold: 85,
    notes: "Backup storage unit",
  },
  {
    id: "F3",
    name: "Long-term Storage",
    location: "Storage Room",
    temperature: "-150°C",
    capacity: 1000,
    currentSamples: 234,
    status: "operational",
    lastMaintenance: "2024-01-12",
    nextMaintenance: "2024-04-12",
    alertsEnabled: true,
    temperatureAlerts: true,
    maintenanceAlerts: true,
    capacityThreshold: 95,
    notes: "Ultra-low temperature storage for long-term samples",
  },
  {
    id: "F4",
    name: "Research Freezer",
    location: "Research Lab",
    temperature: "-80°C",
    capacity: 400,
    currentSamples: 298,
    status: "maintenance",
    lastMaintenance: "2024-01-05",
    nextMaintenance: "2024-02-05",
    alertsEnabled: false,
    temperatureAlerts: false,
    maintenanceAlerts: true,
    capacityThreshold: 80,
    notes: "Currently under maintenance - compressor replacement",
  },
]
